### ISSUE TITLE
hevelius binary is broken

### ISSUE THREAD

**Issue by tomaszmrugalski** [tomaszmrugalski/hevelius-backend#34]
```
$ bin/hevelius 
Traceback (most recent call last):
  File "/home/thomson/devel/hevelius-backend/bin/hevelius", line 16, in <module>
    from hevelius.cmd_repo import repo
  File "/home/thomson/devel/hevelius-backend/hevelius/cmd_repo.py", line 6, in <module>
    from astropy.io import fits
ModuleNotFoundError: No module named 'astropy'
```

**Comment by tomaszmrugalski** [comment]
Fixed in #37.
